package(
    default_visibility = ["//src:__subpackages__"],
)

android_library(
    name = "LaunchTapasTest",
    srcs = [
        "LaunchTapasTest.java",
    ],
    manifest = "AndroidManifest.xml",
    resource_Files = glob(["res/**"]),
)
